title: Faissal IZERMINE
logo: /assets/img/picture_web.jpg
description: MVA Master’s Student (ENS Paris-Saclay)  & École des Ponts et Chaussées (Institut polytechnique de Paris)
show_downloads: false
theme: jekyll-theme-minimal
